name: EnchantmentRework
main: land.euko.enchantrework.Main
version: "1.0"
api-version: "1.21"
author: Tokishu
folia-supported: true
description: Reworking enchantment mechanics to increase gameplay difficulty
website: https://euko.land

commands:
  enchantrework:
    usage: /enchantrework reload
    permission: enchantrework.reload
    aliases: [er, enchrew]

permissions:
  enchantrework.reload:
    default: op
